name: Prettier
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  prettier-fix:
    if: github.actor != 'github-actions[bot]' # Run only if the actor is not the GitHub Actions bot
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Format Code
        uses: HorizonCode/prettier-fix@1.0
